[mysql]
host = "mysql://avnadmin:AVNS_RZDgcXOy7e_VdETAERG@mysql-1b1dd353-mnvvargas3-0969.g.aivencloud.com:18929/defaultdb?ssl-mode=REQUIRED"
port = 18929
user = "avnadmin"
password = "AVNS_RZDgcXOy7e_VdETAERG"
database = "defaultdb"