[mysql]
host = "mysql-1b1dd353-mnvvargas3-0969.g.aivencloud.com"
port = 18929
user = "avnadmin"
password = "AVNS_RZDgcXOy7e_VdETAERG"
database = "defaultdb"

[login]
usuario = "47809672"
clave = "mnv2007vargas"